### ISSUE TITLE
[Request] update information about "Cooking a Deliveroo clone with Next.js (React), GraphQL, Strapi and Stripe"

### ISSUE THREAD

**Issue by JurajJakubov** [strapi/strapi-examples#145]
Hello i want to ask if are there any updates about new version of this "Cooking a Deliveroo clone with Next.js (React), GraphQL, Strapi and Stripe".
It will be very nice through those hard times to have this updated and workable.
I will be thankful for any information about this.

**Comment by RileyMShea** [comment]
Yes, it's possible I've missed something, but the current tutorial appears to stop working by the time it gets to the end of part-2 https://strapi.io/blog/strapi-next-restaurants/

Specifically even when I try to clone this repo I am getting this output from `yarn dev`:

```bash
This dependency was not found:

* next-server/dist/lib/utils in ./node_modules/next-apollo/dist/link.js
```

Which I  found a way to alleviate from https://github.com/adamsoffer/next-apollo/issues/25 by updating `next` to `^8.0.2` and `next-apollo` to `^2.0.9` but then just ran into other errors.

I would target a base minimum of having a freshly cloned repo example/tutorial folder run without issues.  More ideally, have tagged tagged checkpoints for each section of the tutorial in a working state.

I think these tutorials should really be either: fully updated every 6 months, or marked archived.  I'd argue that  in its current state this broken example tutorial hurts strapi more than it helps it since it ,appears to, lead users down a frustrating dead-end.

**Comment by JurajJakubov** [comment]
More information here - https://github.com/strapi/community-content/issues/28

**Comment by RazvanCretu** [comment]
Any new update on how to solve this? I'm encountering the same problem.
