### ISSUE TITLE
cheesecakes example fails to load data, home page empty

### ISSUE THREAD

**Issue by victorkane** [strapi/strapi-examples#16]
**Node.js version**:

9.8.0

**npm version**:

5.7.1

**Strapi version**:

"strapi": "3.0.0-alpha.10"

**Operating system**:

Ubuntu 14.04.5 LTS

**Which example is causing problem?**

cheesecake example

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`npm start` gives errors and no cakes on homepage!

```
(node:1523) UnhandledPromiseRejectionWarning: ValidationError: Cake validation failed: price: Path `price` is required.
    at new ValidationError (/home/durabledrupal/try-stuff/try-strapi/strapi-examples/cheesecakes/node_modules/mongoose/lib/error/validation.js:27:11)
    at model.Document.invalidate (/home/durabledrupal/try-stuff/try-strapi/strapi-examples/cheesecakes/node_modules/mongoose/lib/document.js:1700:32)
    at /home/durabledrupal/try-stuff/try-strapi/strapi-examples/cheesecakes/node_modules/mongoose/lib/document.js:1572:17
    at /home/durabledrupal/try-stuff/try-strapi/strapi-examples/cheesecakes/node_modules/mongoose/lib/schematype.js:785:9
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

Database is successfully created in mongodb, collections created, but they are all empty except core-store:

```
> db.core_store.find()
{ "_id" : ObjectId("5aa592cdc54fd4059cf43b9c"), "key" : "plugin_users-permissions_grant", "environment" : "", "tag" : "", "value" : "{\"email\":{\"enabled\":true,\"icon\":\"envelope\"},\"facebook\":{\"enabled\":false,\"icon\":\"facebook-official\",\"key\":\"\",\"secret\":\"\",\"callback\":\"/auth/facebook/callback\",\"scope\":[\"email\"]},\"google\":{\"enabled\":false,\"icon\":\"google\",\"key\":\"\",\"secret\":\"\",\"callback\":\"/auth/google/callback\",\"scope\":[\"email\"]},\"github\":{\"enabled\":false,\"icon\":\"github\",\"key\":\"\",\"secret\":\"\",\"redirect_uri\":\"/auth/github/callback\",\"scope\":[\"user\",\"user:email\"]},\"twitter\":{\"enabled\":false,\"icon\":\"twitter\",\"key\":\"\",\"secret\":\"\",\"callback\":\"/auth/twitter/callback\"}}", "type" : "object", "__v" : 0 }
{ "_id" : ObjectId("5aa592cdc54fd4059cf43b9d"), "key" : "core_application", "environment" : "", "tag" : "", "value" : "{\"name\":\"Default Application\",\"description\":\"This API is going to be awesome!\"}", "type" : "object", "__v" : 0 }
{ "_id" : ObjectId("5aa592cdc54fd4059cf43b9e"), "key" : "plugin_users-permissions_email", "environment" : "", "tag" : "", "value" : "{\"reset_password\":{\"display\":\"Email.template.reset_password\",\"icon\":\"refresh\",\"options\":{\"from\":{\"name\":\"Administration Panel\",\"email\":\"no-reply@strapi.io\"},\"response_email\":\"\",\"object\":\"­Reset password 🔑 \",\"message\":\"<p>We heard that you lost your password. Sorry about that!</p>\\n\\n<p>But don’t worry! You can use the following link to reset your password:</p>\\n\\n<p><%= URL %>?code=<%= TOKEN %></p>\\n\\n<p>Thanks.</p>\"}}}", "type" : "object", "__v" : 0 }
{ "_id" : ObjectId("5aa592cdc54fd4059cf43b9f"), "key" : "plugin_users-permissions_advanced", "environment" : "", "tag" : "", "value" : "{\"unique_email\":true,\"allow_register\":true}", "type" : "object", "__v" : 0 }
```

**If the current behavior is a bug, please provide the steps to reproduce the problem**

```
git clone git@github.com:strapi/strapi-examples.git
cd strapi-examples/cheesecakes
npm install
npm start
```

**What is the expected behavior?**

cakes on front page, no errors upon initializing data on first run.

**Comment by lauriejim** [comment]
Okay I will take a look.

**Comment by victorkane** [comment]
Thanks so much, I'm really interested in Strapi, and this example can really give me a helping hand to get started on my first projects.

**Comment by nicroto** [comment]
I am hitting this same issue. +1 for fix, so we can check the example out. Cheers!

**Comment by domanieq** [comment]
I am hitting the same issue.. I have no clue how to connect my website with node.js and Strapi so I was really happy with this tutorial.. Such a shame it doesnt work..

**Comment by amouratoglou** [comment]
It doesn't work for me either...

```
WARN (26464 on agustin): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (26464 on agustin): Perhaps you forgot to call it?


```

**Comment by lauriejim** [comment]
Hello guys. I fixed data type for cheesecake price.
And I update setup steps in the readme to let you able to use the app.

Issue still happening on reviews but it's not linked to this issue.

Let me know if you are able to setup the app

**Comment by domanieq** [comment]
Hi, I'm still not able to setup the app.. It's not possible to go to the /admin.. It just returns the homepage so I can not set any permissions or whatsoever..

**Comment by nicroto** [comment]
@domanieq Have you checked the new setup in the readme?

@lauriejim I managed to run it, thanks. Can you please direct me to read some documentation on what exactly happens in this setup and plugin building? (it took... likely over 10 min, so I wonder how would that work in deployment)

**Comment by domanieq** [comment]
@nicroto yes, I think i did..


**1 — Clone the repository.**

git clone git@github.com:strapi/strapi-examples.git
-> That already gave me an error, so I just downloaded the Zip

**2 — Go to the cheesecakes example and install the dependencies.**

cd cheesecakes
npm run setup --plugins
# It can take few minutes

-> This gave me another error namely: npm run setup --plugins

> cheesecakes@0.2.0 setup /Users/domanieq/Downloads/strapi-examples-master/cheesecakes
> cd admin && npm run setup


> strapi-admin@3.0.0-alpha.9 setup /Users/domanieq/Downloads/strapi-examples-master/cheesecakes/admin
> node ./scripts/setup.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nathalie/Downloads/strapi-examples-master/cheesecakes/admin/scripts/setup.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.9 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.9 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/domanieq/.npm/_logs/2018-04-10T10_41_11_711Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cheesecakes@0.2.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cheesecakes@0.2.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/domanieq/.npm/_logs/2018-04-10T10_41_11_733Z-debug.log

**3 — Start the server.**

npm start

-> Wasn't possible because of the previous error, so i did a npm install after which I could to the npm start without errors

**4 — Update permissions.**

You have to go in your admin panel and update permission of the Guest role (Plugins > Users & Permissions > Guest).

Allow these actions:

App:
Info
Cake:
Count
Find
FindOne
Category:
Find
FindOne
Review:
Submit
Find
FindOne
-> But I can't go to the admin panel, since it doesn't show me anything.... The link looks 'broken'. 
When I just download strapi on it's own, I can access the admin panel, so I don't know what is wrong in this download...

**Comment by nicroto** [comment]
That's weird. The error is that shelljs is missing, but it is in the admin plugin's package.json. Perhaps @lauriejim can help out?

**Comment by nicroto** [comment]
I think the cheesecakes package.json needs to change this:
```
  "scripts": {
    "setup": "cd admin && npm run setup"
```
to:
```
  "scripts": {
    "setup": "cd admin && npm install && npm run setup"
```
because the admin setup runs a script that require's shelljs, but nothing has installed it yet.

I think in my case it worked, because the previous version (before the fix spawned from this thread), had `npm install` in the readme and that installs a module, which depends on shelljs (so shelljs is installed too), but maybe even then it worked just because there was a module that needed shelljs internally. 

Can you clear the node_modules dir in cheesecakes and run `npm install` (or even proactively run `npm install --save shelljs`) in it, before calling the `npm run setup --plugins`? (just so you can, hopefully, unblock yourself before the guys at strapi say exactly what's going on).

**Comment by lauriejim** [comment]
@nicroto Can you submit a PR with your update please.

**Comment by nicroto** [comment]
That was the reason for the error, indeed. I hope the pull request is OK. Cheers!

**Comment by domanieq** [comment]
Thank you very much @nicroto !!! :)
@lauriejim is it maybe possible to make a tutorial about how to connect strapi with a HTML-site?
I will try to find it out myself, but would be nice of you have this kind of documentation. I've build a HTML-site myself, but I'm relatively new to coding :)

**Comment by domanieq** [comment]
@lauriejim : never mind! I'm really impressed by Strapi! I learnt javascript (and node.js) three days ago and managed to set the cakes up myself in my own layout. But I ran across a problem.. Every cake can have a category, and per category I want to set up some special textfield, like for example categorydescription.

So, "Red Velvet Cake" is part of the "Red Cake"-category. This Red Cake category had a field called "categorydescription". But here comes the problem. In the index.html page I want to show ${categorydescription} but ofcourse, that item isn't defined in /cake (the $.ajax). I managed a way to copy index.js and replace all the values so that I can show ${categorydescription}. But when I want to merge all the functions together (so be able to call ${categorydescription} AND ${item.name} I get an error. Logically because my variable is local, but I have completely no clue how to fix this..

This is my code:

`var $ = jQuery;

$(document).ready(() => {
  // Get url params
  const url = new URL(window.location.href);
  const page = parseInt(url.searchParams.get('page')) || 1;
  const sort = url.searchParams.get('sort') || 'id';

  const col = 3;
  
    // Get auction data.
    const requestauction = (params = '') => {
      $('.auction').html('');
  
      // Params can be:
      // _sort=id || _sort=price:asc || _sort=price:description -> To order results
      // _start=0&_limit=3 -> To get data from 0 to 4, usefull for pagination
      $.ajax({
        url: `/auction?${params}`,
        method: 'GET',
        success: (data) => {
          for (let j = 0; j < data.length; j++) {
  
            const itemauction = data[j];
            let datestartconvert = data[j].startdate;
            let eventstartdate = new Date(datestartconvert);
            let startmins = ('0'+eventstartdate.getMinutes()).slice(-2);
            let starthours = ('0'+eventstartdate.getHours()).slice(-2);
            let startmonth = ('0'+eventstartdate.getMonth()).slice(-2);
            let startday = ('0'+eventstartdate.getDate()).slice(-2);
            let startauction = startday + "/" + startmonth+ "/" + eventstartdate.getFullYear() + " " + starthours + ":"+ startmins;
  
            let dateendconvert = data[j].enddate;
  
            const first = (j % col === 0) ? 'first' : '';
            const last = (j % col === col - 1) ? 'last' : '';
  
            domauction = `
            <div class="card-footer horse">
            <small style="color:#010a13;float:left;">Start ${startauction}</small>
            <small style="color:#010a13;float:right;">End ${dateendconvert}</small>
          </div>
            `;
  
            $('.auction').append(domauction);
          }
        },
        catch: (err) => {
          console.log(err);
        }
      });
    } 

   // Get cake data.
   const request = (params = '') => {
    $('.products').html('');

    // Params can be:
    // _sort=id || _sort=price:asc || _sort=price:description -> To order results
    // _start=0&_limit=3 -> To get data from 0 to 4, usefull for pagination
    $.ajax({
      url: `/cake?${params}`,
      method: 'GET',
      success: (data) => {
        for (let i = 0; i < data.length; i++) {
          const item = data[i];
          let birthyear = data[i].birthdate;
          
          let start = new Date(birthyear);
          let yearofbirth = start.getFullYear();

          const first = (i % col === 0) ? 'first' : '';
          const last = (i % col === col - 1) ? 'last' : '';

          const dom = `
            <div class="card horse ${first} ${last}"><a href="/product.html?id=${item._id}">
            <div class="img-container">
            <div class="img-text">
              <div class="col-md-2 pedigree">${item.gender}</div>
            <div class="col-md-8 pedigree">${item.father} x ${item.fathermother}</div>
            <div class="col-md-2 pedigree">${yearofbirth}</div></div>
              <img class="card-img-top horse" src="${item.picture}" alt="Card image cap" style="display: block;
            width: 100%;
            height: auto;box-shadow: 3px 2px 7px 0px rgba(0, 0, 0, 0.4), 0px 3px 8px 0 rgba(0, 0, 0, 0.3);">
            
            </div>
            <div class="card-divider"></div>
            <div class="card-body text-center">
              <h5 class="card-title">${item.name}</h5>
              <h3 class="card-slogan">${item.description}</h3></a>
              <div class="row horse">
              <div class="col-md-2 horse" style="background-color:#9dc0c9;"><p class="horse-info">Current Bid:</p>
              <p class="horse-price">${item.price}</p></div>
              <div class="col-md-7 horse">
                  <button type="button" class="btn btn-light horse">FOLLOW</button>
                  <button type="button" class="btn btn-dark horse">BUY NOW</button>
                  <button type="button" class="btn btn-light horse">BID NOW</button>
              </div>
              <div class="col-md-2 horse" style="background-color:#9dc0c9;"><p class="horse-info">ENDS:</p>
                <p class="horse-counter">04  13  55  23</p>
                <p class="horse-info-counter">day(S)  HOUR(S)  MIN(S)  SEC(S)</p></div>
            </div></div>
            ${domauction}
          </div>
          `;

          $('.products').append(dom);
        }
      },
      catch: (err) => {
        console.log(err);
      }
    });
  }
  

    // Handle sort type.
    $('.orderby').on('change', function (e) {
      const value = $(this).val();
      window.location = `/?sort=${value}&page=${page}`;
    });

      // Auto select active sort type.
  $(`option[value="${sort}"]`).attr('selected', true);

  // Set header infos
  $.ajax({
    url: '/info',
    method: 'GET',
    success: (data) => {
      $('.site-title a').html(data.name);
      $('.site-description span').html(data.description);
    }
  });

  // Call get data with parmas.
  request(`_sort=${sort}&_start=${(page - 1) * col}&_limit=${col}`);

    // Call custom route to get cake count to create pagination..
    $.ajax({
      url: `/cake/count`,
      method: 'GET',
      success: (data) => {
        const pages = Math.ceil(data / col);
  
        for (let i = 1; i <= pages; i++) {
          const item = (i === page) ? `<li><span class="page-numbers current">${i}</span></li>` : `<li><a class="page-numbers" href="?sort=${sort}&page=${i}">${i}</a></li>`
          $('ul.page-numbers').append(item);
        }
  
        if (page + 1 <= pages) {
          $('ul.page-numbers').append(`<li><a class="next page-numbers" href="?sort=${sort}&page=${page + 1}">→</a></li>`);
        }
  
        $('.woocommerce-result-count-show').html(`${(page - 1) * col + 1} - ${(page - 1) * col + col} of ${data}`);
      },
      catch: (err) => {
        console.log(err);
      }
    });
});`
