### ISSUE TITLE
Why write an article for a broken code base?

### ISSUE THREAD

**Issue by mikepuerto** [strapi/strapi-examples#84]
I did not feel any of the questions were relevant to my "issue" I'm just curious as to why [This article on Medium](https://blog.strapi.io/strapi-next-setup/) is NO WHERE near accurate to:  `nextjs-react-strapi-deliveroo-clone-tutorial` ? 

These sorts of things just throw people off as I'm sure you can tell by all the comments. Being that this is an "official" `strapi` article, it only makes sense that you properly write the article and don't leave steps out that appear to be sending everyone for a loop.

**Comment by Pedrock** [comment]
And it has no back-end validation of the payment with Stripe: huge vulnerability!

**Comment by soupette** [comment]
@mikepuerto I agree we are rewriting these articles at the moment!

**Comment by Palgie** [comment]
@soupette Thanks for revisiting these articles. If I could I'd like to put these two ideas forward for the refresh:

- Back-end validation of the payment from Stripe (as @Pedrock mentioned).
- Syncing product records to Stripe to use alongside Stripe Orders API rather than simple Stripe Transactions (Maybe a good way to demonstrate using Strapi lifecycle updates to mirror create / update)

Think these would make a great difference to the end result due to the added benefits.

Excited to see the see the new articles and source!

**Comment by krynv** [comment]
Have these been rewritten & submitted anywhere yet?

**Comment by 8kigai** [comment]
I don't feel like the authentication and authorization should be written like this. Some of the code just don't make sense.
